Update Tox conifguration for more replicable testing environments
felix-hilden/sphinx-codeautolink pull request #117
Opened 2022-10-03 13:42 UTC by Zeitsperre

Related issue: #115 

- [ ] Tests written and passed
- [x] Documentation and changelog entry written, docs build passed
- [ ] All `tox` checks passed

2022-10-07 18:40 UTC, felix-hilden requested changes
Thanks for the suggestions! Some seem good, like setting verbosity and color 👌 but there's one big point that I think needs to be resolved before doing anything else.

2022-10-07 18:49 UTC, Zeitsperre commented on setup.py
> +        "test": test_requirements
Fully understand. I think I'm more accustomed to packaging much more elaborately configurable libraries. I can make the approach much more tox-centric for development from sources.

2022-10-07 18:52 UTC, felix-hilden commented on setup.py
> +        "test": test_requirements
I don't think it has anything to do with Tox! Extras should in my mind be reserved for the extra dependencies of the library itself, not the tooling used to build and test it.

2022-10-07 19:08 UTC, Zeitsperre commented on setup.py
> +        "test": test_requirements
Good point!

2022-10-07 19:31 UTC, felix-hilden requested changes
Alright a bunch of comments this time! Let's talk 👌

2022-10-07 19:31 UTC, felix-hilden commented on pyproject.toml
> +relative_files = true
Why was this added? But now that we're at it, let's add `show_missing = true` to `tool.coverage.report` as well!

2022-10-07 19:31 UTC, felix-hilden commented on requirements/dev.txt
> +doc8>=0.9,<1.0
If we're worried about it, we should pin. If not, let's keep it unbounded even if it's technically beta. Thoughts?

2022-10-07 19:31 UTC, felix-hilden commented on setup.py
> -    # Keep extras in sync with requirements manually
Note that the same goes with documentation build requirements, which also contains `ipython`. Perhaps not all extras are needed in the docs build, but still. If you have any good suggestions on how to make the setup DRY I'm all ears!

2022-10-07 19:31 UTC, felix-hilden commented on tox.ini
> +    coverage run --source=sphinx_codeautolink
Source is explicitly set in `pyproject.toml`. Any reason to do it again here?

2022-10-07 19:31 UTC, felix-hilden commented on tox.ini
> -envlist = flake8,doc8,pydocstyle,coverage
Having a more detailed set of envs is helpful when seeing which linting failed.

2022-10-07 19:31 UTC, felix-hilden commented on MANIFEST.in
> +recursive-include requirements *.txt
```suggestion
graft requirements
```
Good catch 🎉  but should we just get the whole dir instead?

2022-10-07 19:31 UTC, felix-hilden commented on docs/src/release_notes.rst
> +
```suggestion
```
No need to notify users about internal changes, particularly ones just related to dev flow!

2022-10-07 19:31 UTC, felix-hilden commented on requirements/dev.txt
> --r tests
This was recursive to allow for a single `pip install` when developing. We don't build docs in tox, so without this it's ever so slightly awkward to setup first time. Also taking suggestions here! The docs build was disabled because I couldn't make it platform-independent easily: tox-dev/tox#2092

2022-10-07 20:02 UTC, Zeitsperre commented on tox.ini
> +    coverage run --source=sphinx_codeautolink
Yes, this was tripping me up for a little while: when `sphinx-codeautolink` is installed, the folder it installs into the python environment is `sphinx_codeautolink`, not `src`.

When running `coverage`  via `tox`, it examines the libraries that are installed in the `tox` env, and skips anything not found to be part of the `source`, so the reported coverage running checks under `tox` ends up being `0%` without this change.

I've run into this issue in other projects, so I was thankful not to lose a bunch of time on this, but I wish it were documented better by the `coverage` folks.

2022-10-07 20:03 UTC, Zeitsperre commented on tox.ini
> -envlist = flake8,doc8,pydocstyle,coverage
Good point. I see now that you were using this in your GitHub Actions workflow. Will roll this back!

2022-10-07 20:06 UTC, felix-hilden commented on tox.ini
> +    coverage run --source=sphinx_codeautolink
So this is because it would be a non-editable install, is it? Not sure what changed though. Any way to configure tox to just use the package in "src"?

2022-10-07 20:06 UTC, Zeitsperre commented on requirements/dev.txt
> +doc8>=0.9,<1.0
I think I pinned it because I thought it was causing issues, but I just checked again with `doc8==1.0.0` and no issues. Will remove the upper bound.

2022-10-07 20:10 UTC, felix-hilden commented on tox.ini
> -envlist = flake8,doc8,pydocstyle,coverage
No less useful locally as well 👍

2022-10-07 20:17 UTC, Zeitsperre commented on pyproject.toml
> +relative_files = true
This is a useful option when you want to be reporting coverage from _multiple environments_ (in `tox` or other virtualenv-based tools). Given that there's only one call to tox configuration that runs`coverage`, it's not at all needed. Good call.

2022-10-07 20:18 UTC, Zeitsperre commented on MANIFEST.in
> +recursive-include requirements *.txt
On second thought, given that the requirements folder is only useful for the development from source, this needs to be reevaluated. I'll give it some consideration the next time I have a minute.

2022-10-07 20:23 UTC, Zeitsperre commented on tox.ini
> -envlist = flake8,doc8,pydocstyle,coverage
True!

2022-10-07 20:24 UTC, felix-hilden commented on MANIFEST.in
> +recursive-include requirements *.txt
The manifest includes documentation and tests, so it would make sense to include requirements to build docs and run tests. Or did I misunderstand?

2022-12-30 12:42 UTC, felix-hilden commented
Hi! Are you still interested in discussing this?

I pulled the obvious improvements to the commit above already. (MANIFEST.in needed a bunch of improvements as it turns out 😮) But let's have a look at the rest if you're still up for it!

2023-01-08 09:53 UTC, felix-hilden commented on requirements/dev.txt
> --r tests
We now build docs in tox 🥳 so this is less of an issue.

2023-01-08 09:54 UTC, felix-hilden commented on MANIFEST.in
> +recursive-include requirements *.txt
The manifest was fixed a bunch in another commit, this is no longer needed.

2023-01-08 09:57 UTC, felix-hilden commented
I also upgraded all of our tooling quite a bunch, so this is unfortunately becoming a bit stale. But I'd love to hear your thoughts on requirements management and tox builds. I'm still contemplating having more isolated tox envs vs. just using the top-level venv for dev.

If you don't respond soonish, I might close the PR (let's reopen though if you want to continue, no biggie). But no pressure, the ideas have been nice to go over already so thank you for that!

2023-01-12 18:12 UTC, Zeitsperre commented
Hi @felix-hilden,

Please excuse the delay. I'm a bit preoccupied with other tasks at the moment.

I noted many of the recent changes in the packaging here and agree with your direction. Using pyproject.toml files is the next step for more convenient configuration and package management.

I would still push for isolated tox builds, especially now that the installation process has been completely revamped. Making better use of the section for `[project.optional-dependencies]` would really simplify the installation of dependencies. I can submit something that works with that approach if you'd like.

I can see that this PR is nearly obsolete, but if there are things you still find valuable here, let me know and I can re-open a new PR with those changes.

2023-01-12 18:58 UTC, felix-hilden commented
Hi! Thanks for the response, I was looking forward to it 🙏 No worries at all. Indeed, I was quite happy with the tooling upgrade 😄 Isolated tox builds do sound alright (it's just mainly that I need to understand the tradeoff between that and having everything use the top env), but I think I will continue to reject the use of optional dependencies for dev tools for the reasons I laid out above. But it would be equally easy to use `requires = -r requirements/dev` (or whatever the syntax is, if it's available).

If you're unsure and want to avoid unnecessary work, we can discuss it here or in a dedicated issue. But I'll close this MR for now. Thanks again for all the suggestions!

2023-01-12 18:58 UTC, closed without merging