Automatic support for ipython3 code blocks
felix-hilden/sphinx-codeautolink pull request #79
Opened 2021-12-06 18:19 UTC by mgeier

My main goal is to use this extension together with https://nbsphinx.readthedocs.io/ and to make it as easy as possible for others to do so as well.

#75 already helped to avoid having to specify custom CSS classes and this PR avoids having to specify `codeautolink_custom_blocks`.

For reference, here are some changes on the `nbsphinx` side:
https://github.com/spatialaudio/nbsphinx/pull/613
https://github.com/spatialaudio/nbsphinx/pull/614

With those changes in place, the only thing that users have to do is to add `'sphinx_codeautolink'` to `extensions`. And that's exactly the amount they *should* have to do (i.e. I don't want to enable it automatically when loading `nbsphinx`).

----

- [x] Tests written and passed
- [x] Documentation and changelog entry written, docs build passed
- [x] All `tox` checks passed

2021-12-06 21:37 UTC, felix-hilden commented
Thanks for the submission!

The changes look alright and the use case is reasonable. You've even made the `IPython` import dynamic which is nice. Still, I'm a bit hesitant because I don't really like the idea of depending on many external packages, or starting to build a library of parser functions. I'm not entirely sure why though, so if you have any insight into how these kinds of situations have been handled in other extensions I'd greatly appreciate it. For example, the reason I included matplotlib's `plot_directive` in #45 was because it already worked out of the box. And Oriol actually implemented a virtually identical parser as a result of the custom block addition, which was developed for this IPython case specifically.

Maybe if we go this route of starting to add additional parsers, we could make a submodule out of the parsers. And certainly IPython is one of the more popular Python syntax supersets.

I'll think about it!

2021-12-07 20:11 UTC, mgeier commented
> Still, I'm a bit hesitant because I don't really like the idea of depending on many external packages, ...

Understandable. I still think it's worth it.

> ... or starting to build a library of parser functions.

Why not?

The list of the most common parsers will be very short, you don't have to implement any exotic formats.

> I'm not entirely sure why though, so if you have any insight into how these kinds of situations have been handled in other extensions I'd greatly appreciate it.

In my own extensions I try to make their usage as simple as possible.

For many people, using Sphinx is on its own already very complicated, and every extension that has cryptic custom settings makes the situation even more complicated. If it's too complicated, many users will simply give up, which would be a pity.

I see no reason why adding `'sphinx_codeautolink'` to `extensions` shouldn't be sufficient. This is exactly how I would expect it to work.

If you don't implement it here, I will implement it in `nbsphinx`. However, there it would be much more complicated and hacky (especially when trying to avoid the caching problem described in #76), so I'd really prefer if it could be implemented here.

> Maybe if we go this route of starting to add additional parsers, we could make a submodule out of the parsers.

I'm not sure if that's worth it for a few lines of code.

And do you even expect requests for any other Python dialects?

Cython? SageMath?

I think the list is very short.

2021-12-08 07:16 UTC, felix-hilden commented
That's fair, I think I've turned around. Honestly I don't quite know about more esoteric Python dialects, but they are just that: esoteric. As you said, I wouldn't honestly expect much more than IPython.

I'm thinking here's what we should do:
- add an install extra for IPython
- add checks to only parse IPython blocks when the import would succeed
- document all of this

This would result in the following: users would install `sphinx-codeautolink[ipython]` if they don't already have it installed, then simply activating the extension enables our version of IPython parsing. How does that sound?

2021-12-08 20:36 UTC, mgeier commented
Sounds good!

I'm just not sure how to best make the `import` check. I've created e354b6cfe7f9a547df76e1588f091125388fd224 as a possible implementation, but maybe you have a better idea?

2021-12-08 20:39 UTC, mgeier commented
BTW, what's the `'py'` type? It doesn't seem to be handled as `highlight-py`CSS class, but it seems to be parsed?

2021-12-08 21:05 UTC, felix-hilden commented
Thanks for the update! I'll probably edit this branch to finish the work as I laid out above.

The `py` lexer is simply an alias of `python`. Both are valid language parameters in code blocks!

2021-12-08 21:13 UTC, mgeier commented
> I'll probably edit this branch to finish the work as I laid out above.

I can finish it, no problem. I just wanted to wait for your comments.

> The `py` lexer is simply an alias of `python`. Both are valid language parameters in code blocks!

Interesting, I didn't know that!

But then I've found a bug: The CSS class `highlight-py` is not correctly handled.

I can fix this while I'm at it ...

2021-12-08 21:39 UTC, felix-hilden requested changes
Alright, reviews are fine to me 😄 Here are some initial ones.

Big picture items:
- Docs
- Tests with IPython

2021-12-08 21:39 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +BUILTIN_BLOCKS = {}
Let's define this only after the two definite functions, so that we don't have to add elements one by one.

2021-12-08 21:39 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    from IPython.core.inputtransformer2 import TransformerManager
We don't need to use a dynamic import here if we test the import already!

2021-12-08 21:39 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    import IPython
So here we could import the transformer directly. That also would make `else` unnecessary. We could also def the function here, but that's debatable.

2021-12-08 21:39 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    block_types = BUILTIN_BLOCKS.keys() | custom_blocks.keys()
Currently this includes `py` as well, which is not correct.

2021-12-08 21:39 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +BUILTIN_BLOCKS['py'] = default_transform
`py` probably shouldn't be a transformer because below we (now correctly, and nicely done 👍) use the builtin transformers to generate CSS classes.

2021-12-09 08:35 UTC, mgeier commented on src/sphinx_codeautolink/extension/block.py
> +    block_types = BUILTIN_BLOCKS.keys() | custom_blocks.keys()
Why is this not correct?

This is the bug fix I was talking about.

Without `'py'`, the CSS class `highlight-py` is not taken into account, which means that `.. code:: py` code blocks don't get any links.

2021-12-09 08:52 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    block_types = BUILTIN_BLOCKS.keys() | custom_blocks.keys()
Oh my bad, I missed your point entirely. And nice catch! We should also add a test for that. I verified this locally with:

```
test_project
test_project.bar
# split
# split
Test project
============

.. code:: py

   import test_project
   test_project.bar()

.. automodule:: test_project
```

2021-12-09 08:54 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    block_types = BUILTIN_BLOCKS.keys() | custom_blocks.keys()
Actually I'll push a quick fix and you can rebase on top of that, so that we can separate the issues. Nevermind adding the test in this.

2021-12-09 08:58 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    block_types = BUILTIN_BLOCKS.keys() | custom_blocks.keys()
Issue in #81 and now pushed.

2021-12-09 17:40 UTC, mgeier commented on src/sphinx_codeautolink/extension/block.py
> +BUILTIN_BLOCKS = {}
I kinda prefer to define global variables close to the top of the file ... in c80f1637d26f649bab623798dea88ac158c8cfab I'm suggesting to get rid of `default_transform()`, which allows both: having the definition at the top and it already containing the two main entries.

What do you think?

2021-12-09 17:42 UTC, mgeier commented on src/sphinx_codeautolink/extension/block.py
> +    from IPython.core.inputtransformer2 import TransformerManager
Actually, we do.

If somebody wants to use the function `clean_ipython()` manually, they would otherwise get a (confusing) `NameError` instead of a (hopefully helpful) `ImportError`.

2021-12-09 17:46 UTC, mgeier commented on src/sphinx_codeautolink/extension/block.py
> +    import IPython
> So here we could import the transformer directly.

Yeah, I thought about that.

But this would break the external usage of `clean_ipython()` (see my previous comment above).

> That also would make `else` unnecessary.

Well, `else` is never strictly necessary.
I just like to make the `try` block as small as possible, moving the stuff that doesn't have to be there into the `else` block.

But we can drop the `else` either way, if you prefer that.

> We could also def the function here, but that's debatable.

Yeah, I thought about that.

But again, this would make it harder to use the function externally.

2021-12-10 07:10 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +BUILTIN_BLOCKS = {}
That actually looks quite nice 👍

2021-12-10 07:27 UTC, felix-hilden requested changes
Getting there!

We probably ought to add at least a mention of this, if not a full example to our docs under "IPython blocks". Perhaps between doctest and third-party blocks since it's more third-party than `doctest` but less than `matplotlib` 😄

2021-12-10 07:27 UTC, felix-hilden commented on docs/src/reference.rst
> +``pycon`` and ``iypthon`` code blocks.
```suggestion
``pycon`` and ``ipython`` code blocks.
```

2021-12-10 07:27 UTC, felix-hilden commented on setup.py
> +        "ipython",
We should definitely not use the `tests` extra for this, because we want users to be able to install it. Let's create another extra called `ipython` instead.

2021-12-10 07:27 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    from IPython.core.inputtransformer2 import TransformerManager
That's a good point, and better that way.

2021-12-10 07:27 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +    import IPython
Yep, after promoting this to be public as well, this makes more sense.

2021-12-10 07:27 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +        transformer = self.custom_blocks.get(language)
```suggestion
        transformer = self.custom_blocks[language]
```
If we get without default, it might as well be a subscript.

2021-12-10 07:27 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
>          self.custom_blocks.update(custom_blocks)
```suggestion
        self.transformers = BUILTIN_BLOCKS.copy()
        self.transformers.update(custom_blocks)
```

I think the name is now outdated. Also I noticed that we've updated the original dict until now 😅 so let's be proper even though it wouldn't be a problem in practice. Of course, this would introduce changes below as well.

2021-12-10 18:25 UTC, mgeier commented on setup.py
> +        "ipython",
I've added it here because I've added a test case which needs IPython. I guess if I wouldn't do that, CI wouldn't pass (but I didn't actually check whether that's true).

I completely forgot about the `[ipython]` extra requirement, I've added it in 08f415c1dbbeee7a962d91036127d69f15018dc7.

2021-12-10 18:28 UTC, mgeier commented on src/sphinx_codeautolink/extension/block.py
> +        transformer = self.custom_blocks.get(language)
Your argumentation is wrong, but you are right.
Since all languages are now handled consistently in a single list, we know that all of them are present in the dictionary.

2021-12-10 18:30 UTC, mgeier commented on src/sphinx_codeautolink/extension/block.py
>          self.custom_blocks.update(custom_blocks)
Good catch!

2021-12-10 18:38 UTC, felix-hilden commented on setup.py
> +        "ipython",
The CI installs "dev" extras, which is all of them, without any intervention!

2021-12-10 18:42 UTC, felix-hilden commented on src/sphinx_codeautolink/extension/block.py
> +        transformer = self.custom_blocks.get(language)
Wait, what do you mean?

2021-12-10 18:49 UTC, mgeier commented
> We probably ought to add at least a mention of this, if not a full example to our docs under "IPython blocks".

I'm not sure if we should mention this.

The problem is that I don't know a realistic example where I would want to use the `ipython3` language in an explicit reST code block.
Do you know one?

For me, this is mostly relevant in combination with other extensions (like e.g. `nbsphinx`), and users don't really need documentation about this.

Of course we could add a Jupyter notebook to the docs, but this seems a bit much.

2021-12-10 18:52 UTC, felix-hilden commented
I think either is fine, although a short IPython syntax code block is totally fine. Users are probably able to extrapolate the use case to their notebooks. But we definitely will add some example about this 😄 Just the same toy code will do, preferably with some of those magic lines.

2021-12-13 20:28 UTC, mgeier commented on setup.py
> +        "ipython",
OK, that seems strange. Is this a common behavior?

Anyway, I would expect that pip-installing `-e .[tests]` would get me the requirements for running the tests, so this should give me all necessary dependencies, including IPython.

Same for `docs`, which I've included here: e48b20024d2412988da1d832b95f0f2f082f33fc.

2021-12-13 20:29 UTC, mgeier commented
I've added a small section about IPython to the docs: dfa6220bac933f221c135d81d3ecd6ad3babe8ab.

2021-12-14 10:24 UTC, felix-hilden commented on docs/src/examples.rst
> +separate Sphinx extensions like nbsphinx_ or MyST-NB_.
😉

2021-12-14 10:39 UTC, felix-hilden commented on setup.py
> +        "ipython",
That's pretty fair, I've not dealt with proper extras much. This could actually warrant a closer look at how we manage the dev environment vs optimise CI installs in general. But I think this is fine for now. I'll have another look in #83.

2021-12-14 10:48 UTC, felix-hilden approved these changes
Yep, I think this is ready to go! Thanks for being patient with me and quick with the updates 👍

2021-12-14 10:49 UTC, merged

2021-12-14 20:25 UTC, mgeier commented
No problem, I like a thorough review!

Thanks for merging!